import module from './module.def.js';
import userServer from './user.server.js';
import membershipDataCtrl from './membership/membership-data/membership-data.controller.js';
import membershipDataHtml from './membership/membership-data/membership-data.html';
import communityNavDir from './membership/component/community-nav.directive.js';
import custompacketCtrl from './membership/dialog/custompacket.controller.js';
import addmessageCtrl from './membership/dialog/addmessage.controller.js';
import delcommonCtrl from './membership/dialog/delcommon.controller.js';
import updatePodctrl from './membership/update-pod/update-pod.controller.js';
import updatePodHtml from './membership/update-pod/update-pod.html';
import membercouponCtrl from './membership/dialog/membercoupon.controller.js';
import balanceCtrl from './asset/balance/balance.controller.js';
import balanceHtml from './asset/balance/balance.html';
import addMoneyCtrl from './asset/balance/dialog/add-money.controller.js';
import integralCtrl from './asset/integral/integral.controller.js';
import membershipRightsCtrl from './interests/membership-rights/membership-rights.controller.js';
import membershipRightsHtml from './interests/membership-rights/membership-rights.html';
import goodsDiscountCtrl from './interests/goods-discount/goods-discount.controller.js';
import goodsDiscountHtml from './interests/goods-discount/goods-discount.html';
import goodsDiscountEditCtrl from './interests/goods-discount/dialog/goods-discount-edit.controller.js';
import definedIconCtrl from './interests/defined-interests/dialog/defined-icon.controller.js';
import addGoodsDiscountCtrl from './interests/goods-discount/add-goods-discount.controller.js';
import addGoodsDiscountHtml from './interests/goods-discount/add-goods-discount.html';
import goodsDiscounManageCtrl from './interests/goods-discount/goods-discount-manage.controller.js';
import goodsDiscounManageHtml from './interests/goods-discount/goods-discount-manage.html';
import editMultiGoodsCtrl from './interests/goods-discount/dialog/edit-multi-goods.controller.js';
import editSingleGoodsCtrl from './interests/goods-discount/dialog/edit-single-goods.controller.js';
import addGoodsDiscountRuleCtrl from './interests/goods-discount/dialog/add-goods-discount-rule.controller.js';
import batchEditGoodsCtrl from './interests/goods-discount/dialog/batch-edit-goods.controller.js';
import addGoodsCtrl from './interests/goods-discount/add-goods.controller.js';
import consumptionDiscountCtrl from './interests/consumption-discount/consumption-discount.controller.js';
import consumptionDiscountEditCtrl from './interests/consumption-discount/dialog/consumption-discount-edit.controller.js';
import addConsumptionDiscountCtrl from './interests/consumption-discount/dialog/add-consumption-discount.controller.js';
import priorityGoodsCtrl from './interests/priority-goods/priority-goods.controller.js';
import safeguardingRightsCtrl from './interests/safeguarding-rights/safeguarding-rights.controller.js';
import preemptionCtrl from './interests/preemption/preemption.controller.js';
import definedInterestsCtrl from './interests/defined-interests/defined-interests.controller.js';
import customerServiceCtrl from './interests/customer-service/customer-service.controller.js';
import directTrainCtrl from './interests/direct-train/direct-train.controller.js';
import growthValueCtrl from './interests/membership-card/growth-value.controller.js';
import singleCardEditCtrl from './interests/membership-card/single-card-edit.controller.js';
import localCardCtrl from './interests/membership-card/local-card.controller.js';
import wechatCardCtrl from './interests/membership-card/wechat-card.controller.js';
import singleCardCtrl from './interests/membership-card/single-card.controller.js';
import moreCardCtrl from './interests/membership-card/more-card.controller.js';
import selectAppidCtrl from './interests/membership-card/dialog/select-appid.controller.js';
import selectRightsCtrl from './interests/membership-card/dialog/select-rights.controller.js';
import shareSetCtrl from './interests/membership-card/dialog/share-set.controller.js';
import blacklistManageCtrl from './membership/blacklist-manage/blacklist-manage.controller.js';
import blacklistLimitCtrl from './membership/blacklist-manage/dialog/blacklist-limit.controller.js';
import blacklistLimitActionCtrl from './membership/blacklist-manage/dialog/blacklist-limit-action.controller.js';
import crowdListCtrl from './membership/population-division/crowd-list/crowd-list.controller.js';
import addCrowdCtrl from './membership/population-division/crowd-list/add-crowd.controller.js';
import crowdCard.directive from './membership/component/crowd-card.directive.js';
import crowdNav.directive from './membership/component/crowd-nav.directive.js';
import populationClassificationCtrl from './membership/population-division/population-classification/population-classification.controller.js';
import crowdNav.directive from './membership/component/crowd-nav.directive.js';
import marketingLogCtrl from './membership/population-division/marketing-log/marketing-log.controller.js';
import crowdNav.directive from './membership/component/crowd-nav.directive.js';
import singleDiscountCtrl from './goods-discount/single-discount/single-discount.controller.js';
import manageGoodsCtrl from './goods-discount/single-discount/manageGoods.controller.js';
import addGoodsCtrl from './goods-discount/single-discount/addGoods.controller.js';
import importGoodsCtrl from './goods-discount/single-discount/importGoods.controller.js';
import integralHtml from './asset/integral/integral.html';
import addGoodsHtml from './goods-discount/single-discount/addGoods.html';
import manageGoodsHtml from './goods-discount/single-discount/manageGoods.html';
import importGoodsHtml from './goods-discount/single-discount/importGoods.html';
import singleDiscountHtml from './goods-discount/single-discount/single-discount.html';
import addGoodsHtml from './interests/goods-discount/add-goods.html';
import consumptionDiscountHtml from './interests/consumption-discount/consumption-discount.html';
import priorityGoodsHtml from './interests/priority-goods/priority-goods.html';
import safeguardingRightsHtml from './interests/safeguarding-rights/safeguarding-rights.html';
import preemptionHtml from './interests/preemption/preemption.html';
import definedInterestsHtml from './interests/defined-interests/defined-interests.html';
import customerServiceHtml from './interests/customer-service/customer-service.html';
import directTrainHtml from './interests/direct-train/direct-train.html';
import growthValueHtml from './interests/membership-card/growth-value.html';
import singleCardEditHtml from './interests/membership-card/single-card-edit.html';
import localCardHtml from './interests/membership-card/local-card.html';
import wechatCardHtml from './interests/membership-card/wechat-card.html';
import singleCardHtml from './interests/membership-card/single-card.html';
import moreCardHtml from './interests/membership-card/more-card.html';
import blacklistManageHtml from './membership/blacklist-manage/blacklist-manage.html';
import crowdListHtml from './membership/population-division/crowd-list/crowd-list.html';
import addCrowdHtml from './membership/population-division/crowd-list/add-crowd.html';
import crowdCardHtml from './membership/component/crowd-card.html';
import crowdNavHtml from './membership/component/crowd-nav.html';
import populationClassificationHtml from './membership/population-division/population-classification/population-classification.html';
import crowdNavHtml from './membership/component/crowd-nav.html';
import marketingLogHtml from './membership/population-division/marketing-log/marketing-log.html';
import crowdNavHtml from './membership/component/crowd-nav.html';
import singleDiscountHtml from './goods-discount/single-discount/single-discount.html';
import manageGoodsHtml from './goods-discount/single-discount/manageGoods.html';
import addGoodsHtml from './goods-discount/single-discount/addGoods.html';
import importGoodsHtml from './goods-discount/single-discount/importGoods.html';
import './user.less';
import './membership/update-pod/update-pod.less';
import './membership/component/index.less';
import './membership/membership-data/style.less';
import './membership/blacklist-manage/style.less';
import './membership/population-division/style.less';
import './goods-discount/single-discount/style.less';
import './interests/defined-interests/defined-interests.less';
import './interests/safeguarding-rights/safeguarding-rights.less';
import './interests/goods-discount/style.less';
import './interests/membership-card/style.less';
export default () => {
    userServer(module);
    membershipDataCtrl(module);
    membershipDataHtml.run(module);
    communityNavDir(module);
    custompacketCtrl(module);
    addmessageCtrl(module);
    delcommonCtrl(module);
    updatePodctrl(module);
    updatePodHtml.run(module);
    membercouponCtrl(module);
    balanceCtrl(module);
    balanceHtml.run(module);
    addMoneyCtrl(module);
    integralCtrl(module);
    membershipRightsCtrl(module);
    membershipRightsHtml.run(module);
    goodsDiscountCtrl(module);
    goodsDiscountHtml.run(module);
    goodsDiscountEditCtrl(module);
    definedIconCtrl(module);
    addGoodsDiscountCtrl(module);
    addGoodsDiscountHtml.run(module);
    goodsDiscounManageCtrl(module);
    goodsDiscounManageHtml.run(module);
    editMultiGoodsCtrl(module);
    editSingleGoodsCtrl(module);
    addGoodsDiscountRuleCtrl(module);
    batchEditGoodsCtrl(module);
    addGoodsCtrl(module);
    consumptionDiscountCtrl(module);
    consumptionDiscountEditCtrl(module);
    addConsumptionDiscountCtrl(module);
    priorityGoodsCtrl(module);
    safeguardingRightsCtrl(module);
    preemptionCtrl(module);
    definedInterestsCtrl(module);
    customerServiceCtrl(module);
    growthValueCtrl(module);
    singleCardEditCtrl(module);
    localCardCtrl(module);
    wechatCardCtrl(module);
    singleCardCtrl(module);
    moreCardCtrl(module);
    selectAppidCtrl(module);
    selectRightsCtrl(module);
    shareSetCtrl(module);
    blacklistManageCtrl(module);
    blacklistLimitCtrl(module);
    crowdListCtrl(module);
    addCrowdCtrl(module);
    crowdCard.directive(module);
    populationClassificationCtrl(module);
    marketingLogCtrl(module);
    singleDiscountCtrl(module);
    manageGoodsCtrl(module);
    addGoodsCtrl(module);
    importGoodsCtrl(module);
    blacklistLimitActionCtrl(module);
    crowdNav.directive(module);
    crowdNav.directive(module);
    crowdNav.directive(module);
    directTrainCtrl(module);
    integralHtml.run(module);
    addGoodsHtml.run(module);
    manageGoodsHtml.run(module);
    importGoodsHtml.run(module);
    singleDiscountHtml.run(module);
    addGoodsHtml.run(module);
    consumptionDiscountHtml.run(module);
    priorityGoodsHtml.run(module);
    safeguardingRightsHtml.run(module);
    preemptionHtml.run(module);
    definedInterestsHtml.run(module);
    customerServiceHtml.run(module);
    growthValueHtml.run(module);
    singleCardEditHtml.run(module);
    localCardHtml.run(module);
    wechatCardHtml.run(module);
    singleCardHtml.run(module);
    moreCardHtml.run(module);
    blacklistManageHtml.run(module);
    crowdListHtml.run(module);
    addCrowdHtml.run(module);
    crowdCardHtml.run(module);
    populationClassificationHtml.run(module);
    marketingLogHtml.run(module);
    singleDiscountHtml.run(module);
    manageGoodsHtml.run(module);
    addGoodsHtml.run(module);
    importGoodsHtml.run(module);
    crowdNavHtml.run(module);
    crowdNavHtml.run(module);
    crowdNavHtml.run(module);
    directTrainHtml.run(module);
    return module;
};